import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { ScrollView, Text, TouchableOpacity, View } from "react-native";
import tw from "./tailwind";

export default function PrivacyPolicy() {
  const router = useRouter();

  const handleBackPress = () => {
    router.back();
  };

  return (
    <View style={tw`flex-1 bg-[#1A1A1A]`}>
      {/* Header */}
      <View style={tw`flex-row items-center p-4 pt-12`}>
        <TouchableOpacity onPress={handleBackPress} style={tw`mr-4`}>
          <Ionicons name="arrow-back" size={24} color="white" />
        </TouchableOpacity>
        <Text style={tw`text-white text-xl font-bold`}>
          Privacy Policy
        </Text>
      </View>

      {/* Content */}
      <ScrollView 
        style={tw`flex-1 px-4`}
        showsVerticalScrollIndicator={false}
      >
        <View style={tw`pb-8`}>
          {/* Privacy Policy Section */}
          <View style={tw`mb-6`}>
            <Text style={tw`text-white text-lg font-bold mb-3`}>
              Privacy Policy
            </Text>
            <Text style={tw`text-white text-sm leading-6 mb-3`}>
              Education built the Educate Live app as a Commercial app. This SERVICE is provided by Education and is intended for use as is.
            </Text>
            <Text style={tw`text-white text-sm leading-6`}>
              This page is used to inform visitors regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our Service.
            </Text>
          </View>

          {/* Cookies Section */}
          <View style={tw`mb-6`}>
            <Text style={tw`text-white text-lg font-bold mb-3`}>
              Cookies
            </Text>
            <Text style={tw`text-white text-sm leading-6`}>
              Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device's internal memory.
            </Text>
          </View>

          {/* Security Section */}
          <View style={tw`mb-6`}>
            <Text style={tw`text-white text-lg font-bold mb-3`}>
              Security
            </Text>
            <Text style={tw`text-white text-sm leading-6`}>
              We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.
            </Text>
          </View>

          {/* Children's Privacy Section */}
          <View style={tw`mb-6`}>
            <Text style={tw`text-white text-lg font-bold mb-3`}>
              Children's Privacy
            </Text>
            <Text style={tw`text-white text-sm leading-6`}>
              These Services do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13. In the case we discover that a child under 13 has provided us with personal information, we immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do necessary actions.
            </Text>
          </View>

          {/* Contact Us Section */}
          <View style={tw`mb-6`}>
            <Text style={tw`text-white text-lg font-bold mb-3`}>
              Contact Us
            </Text>
            <Text style={tw`text-white text-sm leading-6`}>
              If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us at [App contact information].
            </Text>
          </View>

          {/* Illustration By Section */}
          <View style={tw`mb-6`}>
            <Text style={tw`text-white text-lg font-bold mb-3`}>
              Illustration By
            </Text>
            <Text style={tw`text-white text-sm leading-6`}>
              https://stories.freepik.com
            </Text>
          </View>

          {/* Privacy Policy Generator Section */}
          <View style={tw`mb-6`}>
            <Text style={tw`text-white text-lg font-bold mb-3`}>
              This privacy policy page was created at
            </Text>
            <Text style={tw`text-white text-sm leading-6`}>
              privacypolicytemplate.net and modified/generated by App Privacy Policy Generator
            </Text>
          </View>
        </View>
      </ScrollView>
    </View>
  );
}
